# Generated by Django 2.2.6 on 2019-10-19 11:24

from django.db import migrations, models
import sknf.validators


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0002_auto_20190907_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=128, unique=True, validators=[sknf.validators.check_valid_chars]),
        ),
    ]
