# Generated by Django 2.2.4 on 2019-09-04 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0002_auto_20190904_0249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['-created_date']},
        ),
    ]
