# Generated by Django 2.2.6 on 2019-12-22 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0003_auto_20191019_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['-created_date'], 'verbose_name': 'District', 'verbose_name_plural': 'Districts'},
        ),
        migrations.AlterModelTable(
            name='division',
            table='divisions',
        ),
    ]
