# Generated by Django 2.2.4 on 2020-01-07 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0004_auto_20191222_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['-created_date'], 'verbose_name': 'Division', 'verbose_name_plural': 'Divisions'},
        ),
    ]
