# Generated by Django 2.2.6 on 2019-10-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
        ('class_orientation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classorientation',
            name='topic',
        ),
        migrations.AddField(
            model_name='classorientation',
            name='topic',
            field=models.ManyToManyField(to='topics.Topics'),
        ),
    ]
