# Generated by Django 2.2.6 on 2019-11-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_orientation', '0002_auto_20191026_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classorientation',
            name='student_class',
        ),
        migrations.AddField(
            model_name='classorientation',
            name='place',
            field=models.CharField(choices=[('', '--Select--'), ('1', 'Class'), ('2', 'Community')], default='', max_length=10),
        ),
    ]
