# Generated by Django 2.2.6 on 2019-12-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_orientation', '0003_auto_20191117_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classorientation',
            name='place',
            field=models.CharField(choices=[('1', 'Class'), ('2', 'Community')], default='', max_length=10),
        ),
    ]
