# Generated by Django 2.2.6 on 2020-01-01 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20191102_1112'),
        ('topics', '0002_auto_20191231_0546'),
        ('class_orientation', '0004_auto_20191204_0515'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassOrientation',
            new_name='PeerEducation',
        ),
    ]
