# Generated by Django 2.2.4 on 2020-01-08 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_orientation', '0006_auto_20200105_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peereducation',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school.School'),
        ),
    ]
