USERS_VERBOSE_NAME = 'User'
USERS_VERBOSE_NAME_PLURAL = 'Users'
USERNAME_FIELD_TEXT = 'email'
USER_IMAGE_TEXT = 'images/'
USER_EMAIL_TEXT = 'Username'
USER_FIRST_NAME_TEXT = 'first name'
USER_TYPE_ADMIN = 'admin'
USER_TYPE_HEADMASTER = 'headmaster'
USER_TYPE_MENTOR = 'mentor'
USER_TYPE_HEADMASTER_MENTOR = 'headmaster_mentor'
USER_TYPE_SKLEADER = 'skLeader'
USER_TYPE_SKMEMBER = 'skMember'
USER_EMAIL_VALIDATION_ERROR = 'The given email must be set'
SUPER_USER_STAFF_ERROR='Superuser must have is_staff=True.'
SUPER_USER_SUPERUSER_ERROR = 'Superuser must have is_superuser=True.'
CLASS_FORM_CONTROL = "form-control"
USER_NAME_PLACEHOLDER = 'Username'
PASSWORD_PLACEHOLDER = 'Password'
EMAIL_AUTHENTICATION_ERROR = "Sorry, that login was invalid. Please try again."
EMAIL_REQUIRED_ERROR = "Email is required."
USER_IMAGE_LEVEL_TEXT = 'User image'
USER_IMAGE_VALIDATION_ERROR = "Image files only"
USER_CONFIRM_PASSWORD_ERROR = "Password does not match."
USER_IMAGE_SIZE_ERROR = "Image is too large"
HEADMASTER_IMAGE_LEVEL_TEXT = 'Headmaster image'
SKLEADER_IMAGE_LEVEL_TEXT = 'Sk Leader image'
SIGN_IN_INVALID_ERROR = 'Invalid username or password.'
SIGN_IN_INFO = 'Do you have an account? Sign in here'
SCHOOL_SEARCH_INFO = 'Are you looking for a school?'
SEARCH_MESSAGE = 'Click on a district on the map or search here'
SKNF_WEB_URL = 'www.shornokishoree.org'
SKNF_WEB_INFO = 'To know more about SKNF, please visit '
PERMISSION_ERROR_MESSAGE = 'You have to login first to view this page.'
SIGN_IN_BUTTON_TEXT = 'Sign in'
SCHOOL_SEARCH_BUTTON_TEXT = 'Search'
VERSION_TEXT = 'Version '
COPYRIGHT_TEXT = 'Copyright © 2019.'
ALL_RIGHTS_RESERVED = 'All rights reserved.'
SCHOOL_SEARCH_LIST_TEXT = 'Schools'
SEARCH_LIST_SCHOOL_NAME = 'School Name'
# Edit profile

EDIT_ADMIN_PROFILE_TITLE = "Edit Admin Profile"
EDIT_ADMIN_PROFILE_FORM_TITLE = "Basic Information"
EDIT_ADMIN_PROFILE_NAME = "Name"
EDIT_ADMIN_PROFILE_USERNAME = "Username / Mobile Number"
EDIT_ADMIN_PROFILE_PASSWORD = "Password"
EDIT_ADMIN_PROFILE_CONFIRM_PASSWORD = "Confirm password"
EDIT_ADMIN_PROFILE_CHANGE_BUTTON = "Change"
EDIT_ADMIN_PROFILE_CROP_BUTTON = "Crop"
EDIT_ADMIN_PROFILE_UPLOAD_BUTTON = "Upload"
