# Generated by Django 2.2.4 on 2019-09-14 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headmasters', '0002_auto_20190914_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headmasterprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='headmaster_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
