# Generated by Django 2.2.4 on 2019-09-18 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('headmasters', '0003_auto_20190918_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='headmasterprofile',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='headmasterdetails',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='headmasterdetails',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
