# Generated by Django 2.2.4 on 2019-09-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headmasters', '0003_auto_20190914_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headmasterprofile',
            name='role',
        ),
    ]
