# Generated by Django 2.2.4 on 2019-09-15 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20190915_0543'),
        ('headmasters', '0004_remove_headmasterprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='headmasterprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.School'),
        ),
    ]
