# Generated by Django 2.2.4 on 2019-09-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headmasters', '0005_headmasterprofile_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='headmasterprofile',
            name='image',
            field=models.ImageField(default='null', upload_to='images/'),
            preserve_default=False,
        ),
    ]
