# Generated by Django 2.2.4 on 2019-09-22 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headmasters', '0005_headmasterdetails_headmaster'),
        ('headmasters', '0004_auto_20190918_1140'),
    ]

    operations = [
    ]
