# Generated by Django 2.2.4 on 2019-09-22 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headmasters', '0006_merge_20190922_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headmasterprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
    ]
