# Generated by Django 2.2.4 on 2019-10-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headmasters', '0008_auto_20190930_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='headmasterprofile',
            name='crop_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
