# Generated by Django 2.2.4 on 2019-10-22 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headmasters', '0009_headmasterprofile_crop_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headmasterprofile',
            name='crop_url',
        ),
    ]
