# Generated by Django 2.2.6 on 2020-01-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headmasters', '0011_auto_20200108_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headmasterprofile',
            name='mobile',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
