# Generated by Django 2.2.4 on 2020-01-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headmasters', '0014_auto_20200118_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headmasterprofile',
            name='mobile',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
