# Generated by Django 2.2.4 on 2020-01-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headmasters', '0015_auto_20200119_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headmasterprofile',
            name='mobile',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
