DIVISIONS_VERBOSE_NAME = 'Division'
DIVISIONS_VERBOSE_NAME_PLURAL = 'Divisions'
DIVISION_NAME = 'Division Name'
DIVISION_NAME_VALIDATION_ERROR = 'setCustomValidity("Please enter on alphabets only.")'
DIVISION_DELETE_CONFIRMATION = 'Confirm division deletion'
DIVISION_DELETE_INFO = 'Are you sure you want to delete the division '
DIVISION_CLOSE_BUTTON = 'Close'
DIVISION_DELETE_BUTTON = 'Delete'
DIVISION_UPDATE_BUTTON = 'Update'
DIVISION_LIST_TEXT = 'Division List'
DIVISION_SAVE_BUTTON_TEXT = 'Save'
NEW_DIVISION_TITLE_TEXT = 'New Division'
UPDATE_DIVISION_TITLE_TEXT = 'Update Division'
DIVISION_LIST_ACTION_TEXT = 'Actions'
PAGINATION_NULL_INFO_TEXT = 'Showing 0 to 0 of 0 entries'
PAGINATION_INFO_TEXT = ''

