# Generated by Django 2.2.6 on 2020-01-19 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20191015_0650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
    ]
