# Generated by Django 2.2.6 on 2019-10-15 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0009_auto_20191013_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkMemberProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11)),
                ('student_class', models.CharField(choices=[('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=10)),
                ('roll', models.CharField(max_length=128)),
                ('gender', models.CharField(choices=[('', '--Select--'), ('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.School')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skmember_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkmemberDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(default=django.utils.timezone.now)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School')),
                ('skmember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skmembers.SkMemberProfile')),
            ],
        ),
    ]
