# Generated by Django 2.2.4 on 2019-09-22 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkMemberProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11)),
                ('student_class', models.CharField(max_length=128)),
                ('roll', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.School')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skmember_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
