# Generated by Django 2.2.4 on 2019-09-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skmembers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skmemberprofile',
            name='student_class',
            field=models.CharField(choices=[('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=10),
        ),
    ]
