# Generated by Django 2.2.4 on 2019-09-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skmembers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skmemberprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
