# Generated by Django 2.2.4 on 2019-09-28 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skmembers', '0002_auto_20190925_0627'),
        ('skmembers', '0002_auto_20190925_0845'),
    ]

    operations = [
    ]