# Generated by Django 2.2.6 on 2019-10-13 13:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20190929_1404'),
        ('skmembers', '0005_auto_20191012_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='skmemberprofile',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='skmemberprofile',
            name='gender',
            field=models.CharField(choices=[('', '--Select--'), ('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.CreateModel(
            name='SkmemberDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(default=django.utils.timezone.now)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School')),
                ('skmember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skmembers.SkMemberProfile')),
            ],
        ),
    ]
