# Generated by Django 2.2.4 on 2020-01-08 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skmembers', '0007_auto_20191021_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skmemberdetails',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.School'),
        ),
        migrations.AlterField(
            model_name='skmemberdetails',
            name='skmember',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skmembers.SkMemberProfile'),
        ),
        migrations.AlterField(
            model_name='skmemberprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='school.School'),
        ),
        migrations.AlterField(
            model_name='skmemberprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='skmember_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
