# Generated by Django 2.2.6 on 2020-01-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skmembers', '0008_auto_20200108_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skmemberprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('', '--Select--'), ('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
