# Generated by Django 2.2.6 on 2020-01-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skmembers', '0009_auto_20200114_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skmemberprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='skmemberprofile',
            name='roll',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='skmemberprofile',
            name='student_class',
            field=models.CharField(blank=True, choices=[('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=10, null=True),
        ),
    ]
