# Generated by Django 2.2.6 on 2020-01-15 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skmembers', '0010_auto_20200115_0503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skmemberdetails',
            options={'verbose_name': 'Sk Member Detail', 'verbose_name_plural': 'Sk Member Details'},
        ),
        migrations.AlterModelOptions(
            name='skmemberprofile',
            options={'verbose_name': 'Sk Member', 'verbose_name_plural': 'Sk Members'},
        ),
        migrations.AlterModelTable(
            name='skmemberdetails',
            table='skmember_profile_details',
        ),
        migrations.AlterModelTable(
            name='skmemberprofile',
            table='skmember_profiles',
        ),
    ]
