# Generated by Django 2.2.4 on 2020-01-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skmembers', '0011_auto_20200115_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skmemberprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
