# Generated by Django 2.2.4 on 2020-01-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skmembers', '0012_auto_20200118_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skmemberprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
