# Generated by Django 2.2.4 on 2020-01-20 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skmembers', '0013_auto_20200120_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='skmemberprofile',
            name='email',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='skmemberprofile',
            name='name',
            field=models.CharField(default='', max_length=40, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skmemberprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skmember_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
