# Generated by Django 2.2.4 on 2020-01-29 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skmembers', '0014_auto_20200120_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skmemberprofile',
            name='user',
        ),
    ]
