# Generated by Django 2.2.4 on 2019-09-03 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unions', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='union',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unions.Union'),
        ),
        migrations.AlterField(
            model_name='school',
            name='upazilla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='upazillas.Upazilla'),
        ),
    ]
