# Generated by Django 2.2.4 on 2019-09-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.TextField(max_length=200),
        ),
    ]
