# Generated by Django 2.2.4 on 2019-09-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20190903_0536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.TextField(max_length=264),
        ),
    ]
