# Generated by Django 2.2.4 on 2019-09-08 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20190904_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='districts.District'),
        ),
        migrations.AlterField(
            model_name='school',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='division.Division'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='union',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unions.Union'),
        ),
        migrations.AlterField(
            model_name='school',
            name='upazilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='upazillas.Upazilla'),
        ),
    ]
