# Generated by Django 2.2.4 on 2019-09-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20190908_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
