# Generated by Django 2.2.6 on 2019-10-13 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_schoolpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolpost',
            old_name='image',
            new_name='post_image',
        ),
    ]
