# Generated by Django 2.2.6 on 2019-10-19 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20191013_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolpost',
            options={'ordering': ['-created_date']},
        ),
    ]
