# Generated by Django 2.2.4 on 2019-10-22 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_auto_20191019_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='club_establishment_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
