# Generated by Django 2.2.4 on 2019-10-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_school_club_establishment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='club_establishment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
