# Generated by Django 2.2.4 on 2020-01-08 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20191102_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolpost',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.School'),
        ),
    ]
