# Generated by Django 2.2.6 on 2020-01-18 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_auto_20200108_0851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['-created_date'], 'verbose_name': 'School', 'verbose_name_plural': 'Schools'},
        ),
        migrations.AlterModelOptions(
            name='schoolpost',
            options={'ordering': ['-created_date'], 'verbose_name': 'School Post', 'verbose_name_plural': 'School Posts'},
        ),
        migrations.AlterModelTable(
            name='school',
            table='schools',
        ),
        migrations.AlterModelTable(
            name='schoolpost',
            table='school_posts',
        ),
    ]
