DESCRIPTION_REQUIRED_ERROR = "Description is required."

#Districts Related Strings
DISTRICTS_VERBOSE_NAME = 'District'
DISTRICTS_VERBOSE_NAME_PLURAL = 'Districts'
DISTRICT_NAME = 'District Name'
DIVISION_NAME = 'Divisions'

DIVISION_NAME_TEST = 'Dhaka'
DISTRICT_NAME_TEST = 'Gazipur'
EXCEEDING_LENGTH_DISTRICT_NAME_TEST ='CFJKXDHJCK SHDBSADS DUKDJHSKJDH DSJKDHSJKDH WSHSDGSHGD SHDJSDHSDJIL' \
                                     'JDFHCDJHCDJKCHDAFDCFJKDJLHDS SDHSJHSDFJSD SJDDFHLSDJDFHCDL ASDJKFHDJ' \
                                     'JLCFHSDAJLFCHDJCHDJLDJKLFOFHDJOHFDJLFHNDFJDHF SDHSJFHDJFHDJFHDJFHDJHF'

# #Districts Related Strings