DESCRIPTION_REQUIRED_ERROR = "Description is required."

#Divisions Related Strings
DIVISIONS_VERBOSE_NAME = 'Division'
DIVISIONS_VERBOSE_NAME_PLURAL = 'Divisions'
DIVISION_NAME = 'Division Name'
DIVISION_NAME_VALIDATION_ERROR = 'setCustomValidity("Please enter on alphabets only.")'
DIVISION_NAME_VALIDATION_PATTERN = "[a-zA-Z\s]+"
#Divisions Related Strings

#Districts Related Strings
DISTRICTS_VERBOSE_NAME = 'District'
DISTRICTS_VERBOSE_NAME_PLURAL = 'Districts'
DISTRICT_NAME = 'District Name'
DISTRICT_DIVISION_NAME = 'Division'

DIVISION_NAME_TEST = 'Dhaka'
DISTRICT_NAME_TEST = 'Gazipur'
EXCEEDING_LENGTH_DISTRICT_NAME_TEST ='CFJKXDHJCK SHDBSADS DUKDJHSKJDH DSJKDHSJKDH WSHSDGSHGD SHDJSDHSDJIL' \
                                     'JDFHCDJHCDJKCHDAFDCFJKDJLHDS SDHSJHSDFJSD SJDDFHLSDJDFHCDL ASDJKFHDJ' \
                                     'JLCFHSDAJLFCHDJCHDJLDJKLFOFHDJOHFDJLFHNDFJDHF SDHSJFHDJFHDJFHDJFHDJHF'

# #Districts Related Strings


#Upazilas Related Strings

UPAZILAS_VERBOSE_NAME = 'Upazila'
UPAZILAS_VERBOSE_NAME_PLURAL = 'Upazilas'
UPAZILA_NAME = 'Upazila Name'
UPAZILA_DISTRICT_NAME = 'District'
UPAZILA_DIVISION_NAME= 'Division'


#Upazilas Related Strings