# Generated by Django 2.2.4 on 2019-08-31 08:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2019, 8, 31, 8, 12, 37, 947338, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2019, 8, 31, 8, 12, 37, 948679, tzinfo=utc))),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='districts.Division')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
