# Generated by Django 2.2.4 on 2019-09-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
