# Generated by Django 2.2.4 on 2019-08-31 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='division',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
