# Generated by Django 2.2.6 on 2019-10-22 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0002_auto_20191021_1748'),
        ('districts', '0002_auto_20191022_0232'),
    ]

    operations = [
    ]
