# Generated by Django 2.2.4 on 2019-09-07 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='union',
            options={'ordering': ['-created_date']},
        ),
    ]
