# Generated by Django 2.2.6 on 2019-10-22 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unions', '0004_auto_20191022_0232'),
        ('unions', '0004_auto_20191021_1748'),
    ]

    operations = [
    ]
