# Generated by Django 2.2.4 on 2019-11-03 12:42

from django.db import migrations, models
import sknf.validators


class Migration(migrations.Migration):

    dependencies = [
        ('unions', '0005_merge_20191022_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='union',
            name='name',
            field=models.CharField(max_length=100, validators=[sknf.validators.check_valid_chars]),
        ),
    ]
