# Generated by Django 2.2.6 on 2019-12-30 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unions', '0006_auto_20191103_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='union',
            options={'ordering': ['-created_date'], 'verbose_name': 'Union', 'verbose_name_plural': 'Unions'},
        ),
        migrations.AlterModelTable(
            name='union',
            table='unions',
        ),
    ]
