# Generated by Django 2.2.4 on 2020-01-08 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unions', '0007_auto_20191230_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='union',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='districts.District'),
        ),
        migrations.AlterField(
            model_name='union',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='division.Division'),
        ),
        migrations.AlterField(
            model_name='union',
            name='upazilla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='upazillas.Upazilla'),
        ),
    ]
