# Generated by Django 2.2.4 on 2019-09-15 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
    ]
