# Generated by Django 2.2.4 on 2019-09-22 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190918_1140'),
        ('accounts', '0003_auto_20190921_0642'),
    ]

    operations = [
    ]
