# Generated by Django 2.2.4 on 2019-09-25 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_adminprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='mobile',
        ),
    ]
