# Generated by Django 2.2.4 on 2019-09-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190915_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'headmaster'), (3, 'mentor'), (4, 'headmaster_mentor'), (5, 'skLeader')], default=1),
        ),
    ]
