# Generated by Django 2.2.4 on 2019-10-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20191009_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verifiaction_code',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.CharField(blank=True, default=0, max_length=1, null=True),
        ),
    ]
