# Generated by Django 2.2.4 on 2019-09-24 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkLeaderProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11)),
                ('student_class', models.CharField(choices=[('six', 'SIX'), ('seven', 'SEVEN'), ('eight', 'EIGHT'), ('nine', 'NINE'), ('ten', 'TEN')], max_length=10)),
                ('roll', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='images/')),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.School', unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skleader_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkleaderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(default=django.utils.timezone.now)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School')),
                ('skleader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skleaders.SkLeaderProfile')),
            ],
        ),
    ]
