# Generated by Django 2.2.4 on 2019-09-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skleaders', '0002_skleaderprofile_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skleaderprofile',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
