# Generated by Django 2.2.4 on 2019-09-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skleaders', '0003_auto_20190918_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skleaderprofile',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
