# Generated by Django 2.2.4 on 2019-09-22 08:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20190915_0543'),
        ('skleaders', '0004_auto_20190921_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkleaderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(default=django.utils.timezone.now)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School')),
                ('skLeader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skleaders.SkLeaderProfile')),
            ],
        ),
    ]
