# Generated by Django 2.2.4 on 2019-09-22 11:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skleaders', '0007_auto_20190922_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='skleaderprofile',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
