# Generated by Django 2.2.4 on 2019-09-22 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skleaders', '0008_skleaderprofile_joining_date'),
        ('skleaders', '0005_auto_20190922_0713'),
    ]

    operations = [
    ]
