# Generated by Django 2.2.4 on 2019-09-24 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skleaders', '0010_auto_20190923_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skleaderprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
        migrations.AlterField(
            model_name='skleaderprofile',
            name='student_class',
            field=models.CharField(choices=[('six', 'SIX'), ('seven', 'SEVEN'), ('eight', 'EIGHT'), ('nine', 'NINE'), ('ten', 'TEN')], max_length=10),
        ),
    ]
