# Generated by Django 2.2.4 on 2019-09-29 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skleaders', '0012_auto_20190925_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skleaderprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.School', to_field='school_id'),
        ),
    ]
