# Generated by Django 2.2.4 on 2019-09-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skleaders', '0012_auto_20190925_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='skleaderprofile',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='skleaderprofile',
            name='emergency_contact_person',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
