# Generated by Django 2.2.4 on 2019-10-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skleaders', '0016_auto_20190930_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='skleaderprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
