# Generated by Django 2.2.6 on 2019-10-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skleaders', '0018_auto_20191012_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skleaderprofile',
            name='gender',
            field=models.CharField(choices=[('', '--Select--'), ('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
