# Generated by Django 2.2.4 on 2020-01-08 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skleaders', '0019_auto_20191015_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skleaderdetails',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.School'),
        ),
        migrations.AlterField(
            model_name='skleaderdetails',
            name='skleader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skleaders.SkLeaderProfile'),
        ),
        migrations.AlterField(
            model_name='skleaderprofile',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school.School'),
        ),
        migrations.AlterField(
            model_name='skleaderprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='skleader_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
