# Generated by Django 2.2.6 on 2020-01-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skleaders', '0021_auto_20200114_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skleaderprofile',
            name='mobile',
            field=models.CharField(default='', max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
