# Generated by Django 2.2.4 on 2020-01-15 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skleaders', '0022_auto_20200114_0700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skleaderdetails',
            options={'verbose_name': 'SK Leader Detail', 'verbose_name_plural': 'SK Leader Details'},
        ),
        migrations.AlterModelOptions(
            name='skleaderprofile',
            options={'verbose_name': 'SK Leader', 'verbose_name_plural': 'SK Leaders'},
        ),
        migrations.AlterModelTable(
            name='skleaderdetails',
            table='skleader_profile_details',
        ),
        migrations.AlterModelTable(
            name='skleaderprofile',
            table='skleader_profiles',
        ),
    ]
