# Generated by Django 2.2.4 on 2020-01-15 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skleaders', '0023_auto_20200115_0833'),
        ('skleaders', '0022_auto_20200115_0503'),
    ]

    operations = [
    ]
