# Generated by Django 2.2.4 on 2020-01-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skleaders', '0024_merge_20200115_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skleaderprofile',
            name='mobile',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
