# Generated by Django 2.2.4 on 2019-09-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
        ('club_meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmeetings',
            name='topics',
            field=models.ManyToManyField(to='topics.Topics'),
        ),
        migrations.DeleteModel(
            name='MeetingTopics',
        ),
    ]
