# Generated by Django 2.2.4 on 2019-09-28 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club_meetings', '0002_auto_20190928_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmeetings',
            name='attendance',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clubmeetings',
            name='presence_skleader',
            field=models.BooleanField(default=False),
        ),
    ]
