# Generated by Django 2.2.4 on 2019-10-02 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20190929_1404'),
        ('club_meetings', '0003_auto_20190928_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmeetings',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
    ]
