# Generated by Django 2.2.4 on 2019-10-27 06:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_meetings', '0004_clubmeetings_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmeetings',
            name='attendance',
            field=models.ManyToManyField(related_name='a_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
