# Generated by Django 2.2.6 on 2019-12-31 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_meetings', '0006_clubmeetings_skleader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubmeetings',
            options={'ordering': ['-date'], 'verbose_name': 'Club Meeting', 'verbose_name_plural': 'Club Meetings'},
        ),
        migrations.AlterModelTable(
            name='clubmeetings',
            table='club_meetings',
        ),
    ]
