# Generated by Django 2.2.4 on 2020-01-29 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headmasters', '0016_auto_20200120_0415'),
        ('club_meetings', '0009_auto_20200129_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmeetings',
            name='guide_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='headmasters.HeadmasterProfile'),
        ),
    ]
