HEADMASTER_DETAIL_PAGE_TITLE = 'Headmaster/Guide Teacher Info'
HEADMASTER_NEW_PAGE_TITLE = 'Add New Headmaster/Guide Teacher'
HEADMASTER_LIST_PAGE_TITLE = 'Headmasters/Guide Teachers'
HEADMASTER_UPDATE_PAGE_TITLE = 'Update Headmaster Info'
HEADMASTER_BASIC_INFO = 'Basic Information'
UPDATE_SCHOOL_INFO_BUTTON = 'Update School Information'
UPDATE_BASIC_INFO_BUTTON = 'Update Basic Information'
HEADMASTER_SCHOOL_INFO = 'School Information'
NAME_TEXT = 'Name'
USERNAME_TEXT = 'Username'
MOBILE_TEXT = 'Mobile'
USER_TYPE_TEXT = 'User Type'
SCHOOL_TEXT = 'School'
PROFILE_PIC_TEXT = 'Profile Picture'
CONFIRM_PASSWORD_TEXT = 'Confirm Password'
FROM_TEXT = 'From'
TO_TEXT = 'To'
DIVISION_TEXT = 'Division'
DISTRICT_TEXT = 'District'
UPAZILA_TEXT = 'Upazila'
UNION_TEXT = 'Union'
NEW_HEADMASTER_BUTTON = 'New Headmaster'
EMAIL_TEXT = 'Email'
GENERATE_PASSWORD ='Genarate Password'

<<<<<<< HEAD
#alert messages
NAME_REQUIRED = 'Name is required.'
PASSWORD_REQUIRED = 'Password is required.'
CONFIRM_PASSWORD_REQUIRED = 'Confirm password is required.'
USER_TYPE_REQUIRED = 'User type is required.'
PASSWORD_NOT_MATCHED = "Password does not match."
SCHOOL_REQUIRED = 'School is required.'
MOBILE_LENGTH_EXCEED = 'Moblie Number can not exceed 11 digits'
FROM_DATE_REQUIRED = 'From date is required.'
IMAGE_FILE_SIZE_EXCEED = "Image file too large ( > 1mb )"
=======
HEADMASTER_VERBOSE_NAME = 'Headmaster'
HEADMASTER_VERBOSE_NAME_PLURAL = 'Headmasters'
HEADMASTER_DETAIL_VERBOSE_NAME = 'Headmaster Detail'
HEADMASTER_DETAIL_VERBOSE_NAME_PLURAL = 'Headmaster Details'
>>>>>>> features/admin_skmember
