# Generated by Django 2.2.6 on 2019-12-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduplus_activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduplusactivity',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
