# Generated by Django 2.2.6 on 2019-12-08 04:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eduplus_activity', '0004_remove_eduplusactivity_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduplusTopics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
