# Generated by Django 2.2.6 on 2019-12-18 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skleaders', '0019_auto_20191015_0833'),
        ('eduplus_activity', '0006_eduplusactivity_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduplusactivity',
            name='skleader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skleaders.SkLeaderProfile'),
        ),
    ]
