# Generated by Django 2.2.4 on 2019-12-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduplus_activity', '0007_eduplusactivity_skleader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduplusactivity',
            name='topics',
            field=models.ManyToManyField(to='topics.Topics'),
        ),
    ]
