# Generated by Django 2.2.4 on 2019-12-28 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduplus_activity', '0008_auto_20191228_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduplusactivity',
            name='method',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='eduplus_activity.EduplusTopics'),
            preserve_default=False,
        ),
    ]
