# Generated by Django 2.2.4 on 2020-01-01 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduplus_activity', '0009_eduplusactivity_method'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EduplusTopics',
            new_name='Method',
        ),
    ]
