# Generated by Django 2.2.4 on 2020-01-08 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduplus_activity', '0010_auto_20200101_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduplusactivity',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eduplus_activity.Method'),
        ),
        migrations.AlterField(
            model_name='eduplusactivity',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school.School'),
        ),
        migrations.AlterField(
            model_name='eduplusactivity',
            name='skleader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='skleaders.SkLeaderProfile'),
        ),
    ]
