# Generated by Django 2.2.4 on 2020-01-29 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduplus_activity', '0013_auto_20200118_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eduplusactivity',
            name='attendance',
        ),
    ]
