# Generated by Django 2.2.4 on 2019-09-24 07:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('division', '0001_initial'),
        ('districts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upazilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='districts.District')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='division.Division')),
            ],
        ),
    ]
