# Generated by Django 2.2.4 on 2019-09-02 11:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('districts', '0002_auto_20190831_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upazilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2019, 9, 2, 11, 53, 56, 150772, tzinfo=utc))),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='districts.District')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='districts.Division')),
            ],
        ),
    ]
