# Generated by Django 2.2.4 on 2019-09-02 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upazillas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upazilla',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
