# Generated by Django 2.2.4 on 2019-09-21 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upazillas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upazilla',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='districts.District'),
        ),
        migrations.AlterField(
            model_name='upazilla',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='division.Division'),
        ),
    ]
