# Generated by Django 2.2.4 on 2020-01-07 12:04

from django.db import migrations, models
import sknf.validators


class Migration(migrations.Migration):

    dependencies = [
        ('upazillas', '0005_auto_20191223_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upazilla',
            name='name',
            field=models.CharField(max_length=100, validators=[sknf.validators.check_valid_chars]),
        ),
    ]
