# Generated by Django 2.2.4 on 2020-01-08 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upazillas', '0006_auto_20200107_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upazilla',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='districts.District'),
        ),
        migrations.AlterField(
            model_name='upazilla',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='division.Division'),
        ),
    ]
